docs/learn/faq.md
docs/learn/white-papers/data-policy-europe.md
docs/learn/white-papers/data-policy.md
docs/participate.md
docs/specification/process.md
mkdocs.yml

As mentioned in #24, the links used to connect to slack is out of date. This PR updates to those links to https://share.mobilitydata.org/slack
(+ fixes one typo found)

Update link to slack

---

docs/learn/white-papers/data-policy-europe.md
docs/learn/white-papers/data-policy.md

Adds links to Portugueses, Spanish, and French policy guides for both Europe and the Americas.

Add links to translated policy guides

---

theme_overrides/main.html

MobilityData has acquired the gbfs.org domain, this PR updates the announcement banner to let users know.

gbfs.mobilitydata.org --> gbfs.org

---

docs/specification/reference.md

This PR updates the site [reference.md](https://github.com/MobilityData/gbfs.mobilitydata.org/blob/master/docs/specification/reference.md) with the [gbfs.md](https://github.com/MobilityData/gbfs/blob/master/gbfs.md) spec.

Sync site reference with gbfs.md spec

---

docs/toolbox/resources.md

This PR adds ENTUR's lamassu as software for creating apis to the toolbox resources page.

Add lamassu as software for creating apis

---

docs/specification/reference.md

Change:
- Fix typos in system_alerts.json which was fixed in the spec in https://github.com/MobilityData/gbfs/pull/540
Fixes https://github.com/MobilityData/gbfs.mobilitydata.org/issues/38

Sync GBFS spec typo

---

docs/participate.md

The governance process was moved to a separate file in https://github.com/MobilityData/gbfs/pull/521.
This PR updates the governance process URL on https://gbfs.org/participate/ to the new file (https://github.com/MobilityData/gbfs/blob/master/governance.md).

Update URL to governance process

---

docs/specification/reference.md

At https://gbfs.org/specification/reference/, in the Field Types section, the list doesn’t format correctly after Localized String (after the table with the example).
Before | After
-- | --

Fixed table in specifications

---

mkdocs.yml

A deprecation warning was issued in MKdocs Material 9.4:
```
DeprecationWarning: 'materialx.emoji.to_svg' is deprecated. Material emoji logic
has been officially moved into mkdocs-material version 9.4.
Please use Material's 'material.extensions.emoji.to_svg' as mkdocs_material_extensions
is deprecated and will no longer be supported moving forward. This is the last release.
```
This change fixes it, as defined in https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration

fix: deprecation warning for 2 Python Mkdown ext

---

docs/specification/reference.md

Follow up of https://github.com/MobilityData/gbfs/pull/560
The relative paths are broken when the specs are displayed on https://gbfs.org/specification/reference/.
```
WARNING -  Doc file 'specification/reference.md' contains a relative link 'README.md#current-version-recommended', but the target 'specification/README.md' is not found among documentation
files.
WARNING -  Doc file 'specification/reference.md' contains a relative link 'data-licenses.md', but the target 'specification/data-licenses.md' is not found among documentation files.
WARNING -  Doc file 'specification/reference.md' contains a relative link 'images/geofencing_example.svg', but the target 'specification/images/geofencing_example.svg' is not found among
```
Before | After
-- | --
This PR syncs reference.md with …

Syncs reference.md with gbfs.md

---

docs/specification/index.md
docs/specification/reference.md

There is a version inconsistency between the specification [home page](https://gbfs.org/specification/) (where we say the current version is v3.0-RC) and the [reference](https://gbfs.org/specification/reference/) (where we say the current version is v2.3).
Keep "Current version" for the most recent official version (v2.3).
Use "Latest version" for the most recent version (v3.0-RC2-Draft).
Used OpentTripPlanner [documentation](https://docs.opentripplanner.org/en/v2.4.0/) as inspiration for listing the versions of the documentation on the specification [home page](https://gbfs.org/specification/).
Before | After
-- | --

Update versions on specification index.md

---

docs/specification/index.md

This PR moves the Release Candidate Feature Implementation from the [Github wiki](https://github.com/MobilityData/gbfs/wiki/Release-Candidate-Feature-Implementation) to https://gbfs.org/specification/.
It follows the same implementation as the [GTFS adoption tracker](https://gtfs.org/extensions/fares-v2/#adoption-tracker).
Before | After
-- | --

Release Candidate Feature Implementation

---

docs/specification/index.md

This PR moves the "Extensions Outside of the Specification" tool from the [Github wiki](https://github.com/MobilityData/gbfs/wiki/Extensions-outside-of-the-specification#extensions-outside-of-the-specification) to https://gbfs.org/specification/.
Before | After
-- | --

Extensions Outside of the Specification

---

docs/specification/index.md
docs/specification/reference.md

Fixes https://github.com/MobilityData/gbfs.org/issues/62
This PR syncs reference.md after https://github.com/MobilityData/gbfs/pull/564.
Changes:
- Update extension tracker URL from wiki to gbfs.org

Update extension tracker URL from wiki to gbfs.org

---

docs/index.md
docs/roadmap.md
mkdocs.yml

This PR removes the roadmap from the navigation on https://gbfs.org/ as this section is now displayed on the page https://gbfs.org/participate/#get-involved.
Before | After
-- | --

Remove roadmap from the navigation

---

docs/learn/faq.md
docs/learn/white-papers/data-policy-europe.md
docs/learn/white-papers/data-policy.md
docs/toolbox/index.md
scripts/fetchdata.sh

Some repo URLs were still pointing to the old NABSA repo.
Update repo URLs from NABSA to MobilityData.
Before | After
-- | --
https://github.com/NABSA/gbfs | https://github.com/MobilityData/gbfs/

Update repo URLs from NABSA to MobilityData

---

docs/toolbox/resources.md

This PR adds community libraries and tools to the resources page: https://gbfs.org/toolbox/resources/

Add community libraries and tools

---

docs/specification/index.md

Similarly to [gtfs.org](https://gtfs.org/extensions/fares-v2/#first-adopters), this PR adds a First Adopters section on [gbfs.org](https://gbfs.org/specification/) to highlight the first adopters.

Adds First Adopters section

---

docs/learn/faq.md
docs/participate.md
mkdocs.yml

This PR fixes the redirections of Governance Process and change proposals links.

Fix redirections

---

requirements.txt

No need for it, `mkdocs-static-i18n==1.1.0` does the same job. Probably even conflicts with it.

Removed `mkdocs-i18n==0.4.6`

---

README.md

The URL to submit feedback about gbfs.org was changed by typeform. 
This PR updates the typeform URL in the README.
Before | After
-- | --

Update feedback form URL

---

docs/en/participate.md
docs/fr/participate.md

This PR replaces the roadmap with GBFS-only features from the Productboard portal.
Which pages are affected by this change?
- https://gbfs.org/participate/
- https://gbfs.org/fr/participate/
Before | After
-- | --

Replace roadmap with GBFS-only Productboard portal

---

docs/en/specification/index.md
docs/fr/specification/index.md

This PR adds [Dashboard Deelmobiliteit](https://dashboarddeelmobiliteit.nl/) and [ENTUR](https://entur.no/) as first adopters on https://gbfs.org/specification/#first-adopters.
Before | After
-- | --

Add first adopters

---

requirements.txt

When clicking an anchor in the Table of Contents of the reference on https://gbfs.org/specification/reference/, the links redirect to the raw content on GitHub.
This PR fixes anchors in the reference. 
The reference is fetched by the plugin [mkdocs-embed-external-markdown](https://pypi.org/project/mkdocs-embed-external-markdown/). The plugin [change log](https://github.com/fire1ce/mkdocs-embed-external-markdown?tab=readme-ov-file#changelog) shows that version `3.x.x`:
>Added handling for relative links in the markdown, making them absolute based on the base URL.
We want the relative links to remain relative. So this PR downgrades the plugin to the version preceding this change: `2.3.0`.
**Before**
https://github.com/MobilityData/gbfs.org/assets/2423604/70f34b7b-e1be-4a46-8b63-c2f932ce3850 …

Fix relative URLs in reference

---

docs/en/learn/guide.md
docs/fr/learn/guide.md

This PR fixes a typo in the GBFS Implementation guide (https://gbfs.org/learn/guide/).
A GBFS v3 dataset is composed of up to 12 JSON files. Previous versions were composed of up to 13 files.
Before | After
-- | --

Fix number of JSON files in a GBFS v3 dataset

---

mkdocs.yml

This PR fixes the redirect URLs.
The source of the problem seems to be from commit https://github.com/MobilityData/gbfs.org/pull/78/commits/a4586983628df0f59a2d58383fda368c41c9ed7f.
Before | After (could not test locally)
-- | --
I suggest to merge and test this URL to see if the redirect is fixed: https://gbfs.org/faq should redirect to https://gbfs.org/learn/faq/.
Note that the proposed change generates a warning and I am not able to test locally :

Fix redirects

---

docs/en/specification/index.md

This PR updates the current version to v3.0 on https://gbfs.org/specification/.
Before | After
-- | --

Update current version to v3

---

docs/en/learn/guide.md
docs/en/specification/index.md
docs/en/toolbox/index.md
docs/fr/learn/guide.md
docs/fr/toolbox/index.md

This PR updates the examples in the implementation guide to use v3.0.
It also set the number of systems to 800 after the catalog cleanup in https://github.com/MobilityData/gbfs/pull/622.

Update Implementation Guide to v3.0

---

docs/en/learn/guide.md
docs/en/learn/white-papers/data-policy-europe.md
docs/en/learn/white-papers/data-policy.md
docs/en/specification/index.md
docs/en/toolbox/index.md
docs/fr/learn/guide.md
docs/fr/toolbox/index.md

This PR updates the policy guides to v3.0:
- https://gbfs.org/learn/white-papers/data-policy/
- https://gbfs.org/learn/white-papers/data-policy-europe/

Update policy guides to v3.0

---

docs/en/toolbox/resources.md
docs/fr/toolbox/resources.md

This PR updates the list of language bindings in the resources with TypeScript and Java (https://gbfs.org/toolbox/resources/#language-bindings-for-gbfs)

Update language bindings in the resources

---

docs/en/specification/index.md
docs/en/specification/reference.md
docs/fr/specification/index.md
docs/fr/specification/reference.md

Follows the release of v3.1-RC (https://github.com/MobilityData/gbfs/pull/637 and https://github.com/MobilityData/gbfs/pull/639).
This PR:
- Adds v3.1-RC to the list of versions in https://gbfs.org/specification/
- Points the reference to the latest official versions (v3.0) in https://gbfs.org/specification/reference/
Before | After
-- | --

Add v3.1-RC to the list of versions

---

nginx-access-gbfs-org.conf

The redirections were for the staging environment. These are the correct one for the current prod version.

Fixed redirections

---

docs/en/tools.md
docs/es/tools.md
docs/fr/tools.md

@testower notified MobilityData that Entur no longer maintains a JavaScript package of validator for GBFS. 
Please note that Entur still maintains the [Java implementation](https://central.sonatype.com/artifact/org.entur.gbfs/gbfs-validator-java) of validator for GBFS.
This PR removes Entur's validator JavaScript package from the tools and adds the GBFS validator website to the Validators section:

Update tools validators section

---

docs/en/community.md
docs/es/community.md
docs/fr/community.md

Migrating the public roadmap from Productboard to Airtable for consistency with the Implementation Status on https://gbfs.org/community/.
- Replaced Productboard roadmap with [Airtable](https://airtable.com/appQvTu1nOy6fJwUP/tbltQn9TWPrgmSYQD/viw7GyfAxWWtfB7W9?blocks=hide).
- Removed items that are already in the Implementation Status table and added new issues from [GitHub](https://github.com/MobilityData/gbfs/issues).
Before | After
-- | --

Replace Productboard roadmap with Airtable

---

docs/en/documentation/index.md
docs/es/documentation/index.md
docs/fr/documentation/index.md

v3.1-RC2 will be released in https://github.com/MobilityData/gbfs/pull/761. The gbfs.org website needs to list this new Pre-release version.
This PR bumps the Pre-release version to v3.1-RC2 on https://gbfs.org/documentation/.
Before | After
-- | --
It is expected that the URL https://github.com/MobilityData/gbfs/blob/v3.1-RC2/gbfs.md does not work yet. It will work when https://github.com/MobilityData/gbfs/pull/761 will be merged.

Update Pre-release version to v3.1-RC2
